#!/bin/sh

down() {
brillo -u 150000 -U 4
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "$brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
brillo -u 150000 -A 4
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "$brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
